source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'AdMobUIKitSample' do
  use_frameworks!

  pod 'NimbusSDK', '~> 2', subspecs: [
     'NimbusKit',          # Nimbus SDK
     'NimbusAdMobKit'      # AdMob Bidding Support (Available from 2.22.0)
  ]
end

