name: Build

on:
   pull_request:
     branches:
       - main

jobs:
  build:
    name: Build Project
    runs-on: macos-12

    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app

    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Restore cached Pods
      id: pod-cache
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install pods
      run: pod install --repo-update

    - name: Build project
      run: xcodebuild -workspace "nimbus-ios-sample.xcworkspace" -scheme "nimbus-ios-sample" -configuration "Debug" -sdk "iphonesimulator15.5" ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES
