name: Build

on:
   pull_request:
     branches:
       - main

jobs:
  build:
    name: Build Project
    runs-on: macos-12

    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app

    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install pods
      run: pod install --repo-update

    - name: Build project
      run: xcodebuild -workspace "nimbus-ios-sample.xcworkspace" -scheme "nimbus-ios-sample" -configuration "Debug" -sdk "iphonesimulator16.0" ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES
