name: CocoaPods

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build Project
    runs-on: macos-14
    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_15.3.app

    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Ensure Project does not contain Pods before build
      run: |
        ! grep -q Pods nimbus-ios-sample.xcodeproj/project.pbxproj

    - name: Restore Build Cache
      uses: actions/cache@v4
      with:
        path: |
          Pods
          .build
          !.build/Logs/**
          !.build/TestResults/**
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile*') }}
        restore-keys: |
          ${{ runner.os }}-cocoapods-

    - name: Install pods
      run: pod install --repo-update

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Build Sample App
      run: set -o pipefail && xcodebuild -workspace "nimbus-ios-sample.xcworkspace" -scheme "nimbus-ios-sample-pods" -configuration "Debug" -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15" -derivedDataPath .build/DerivedData | xcbeautify
