name: Build Apps

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  cocoapods:
    name: Build Cocoapods App
    uses: ./.github/workflows/cocoapods.yml

  spm:
    name: Build Swift Package Manager App
    uses: ./.github/workflows/spm.yml

  test:
    needs: spm
    runs-on: ubuntu-latest
    steps:
      - name: Download Release
        uses: actions/download-artifact@v3
        with:
          name: nimbus-ios-sample
          path: nimbus-ios-sample.app

      - name: Checkout Nimbus Mobile QA
        uses: actions/checkout@v3
        with:
          repository: 'timehop/nimbus-mobile-qa'
          path: .maestro
          ref: build/flow
          ssh-key: ${{ secrets.NIMBUS_QA_DEPLOY }}

      - name: Run Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD }}
          app-file: nimbus-ios-sample.app
          env: |
            APP_ID=com.adsbynimbus.ios.NimbusDemo
