name: Swift Package Manager

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build Project
    runs-on: macos-12
    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app

    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Build Sample App
      run: set -o pipefail && xcodebuild -scheme "nimbus-ios-sample" -configuration "Debug" -sdk "iphonesimulator16.2" -derivedDataPath .build/DerivedData | xcbeautify
