name: Swift Package Manager

on:
   pull_request:
     branches:
       - main

jobs:
  build:
    name: Build Project
    runs-on: macos-12
    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.1.app

    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Build Sample App
      run: xcodebuild -scheme "nimbus-ios-sample" -configuration "Debug" -sdk "iphonesimulator16.1"
