name: Swift Package Manager

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build Project
    runs-on: macos-15
    steps:
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.1.app

    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install xcbeautify
      run: brew install xcbeautify
    
    - name: Restore Build Cache
      uses: actions/cache@v4
      with:
        path: |
          .build
          !.build/Logs/**
          !.build/TestResults/**
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.*') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build Sample App
      run: set -o pipefail && xcodebuild -scheme "nimbus-ios-sample" -configuration "Debug" -destination "platform=iOS Simulator,OS=18.6,name=iPhone 16" -derivedDataPath .build/DerivedData | xcbeautify
